name: Build macOS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      flutter_version:
        required: true
        type: string
      xcode_version:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ inputs.flutter_version }}

      - name: Get Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Prepare for macOS
        shell: bash
        run: flutter config --enable-macos-desktop

      - name: Build for macOS
        shell: bash
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ inputs.xcode_version }}.app/Contents/Developer
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs
          chmod +x ./scripts/macos_nosign.sh
          ./scripts/macos_nosign.sh
          flutter build macos
          cd build/macos/Build/Products/Release
          mkdir -p "Void Reader"
          cp -r "Void Reader.app" "Void Reader/Void Reader.app"
          ln -s /Applications "Void Reader/Applications"
          hdiutil create -volname "Void Reader" -srcfolder "Void Reader" -ov -format UDZO Void-Reader-${{ inputs.version }}.dmg
          ditto -c -k --keepParent "Void Reader.app" "Void-Reader-${{ inputs.version }}.zip"

      - name: Rename builds
        run: |
          cd build
          mkdir -p macos
          mv macos/Build/Products/Release/Void-Reader-${{ inputs.version }}.dmg macos/Void-Reader-macos-${{ inputs.version }}.dmg
          mv macos/Build/Products/Release/Void-Reader-${{ inputs.version }}.zip macos/Void-Reader-macos-${{ inputs.version }}.zip
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            build/macos/*.dmg
            build/macos/*.zip
          if-no-files-found: error
